admin_page_page_list:
    path: /page/list
    defaults:
        _controller: PageBundle:Admin/Page:list

admin_page_page_create:
    path: /page/create/{id}
    defaults:
        _controller: PageBundle:Admin/Page:create
        id: null
    requirements:
        id: \d+

admin_page_page_update:
    path: /page/update/{id}
    defaults:
        _controller: PageBundle:Admin/Page:update
    requirements:
        id: \d+

admin_page_page_remove:
    path: /page/remove/{id}
    defaults:
        _controller: PageBundle:Admin/Page:remove
    requirements:
        id: \d+
